apiVersion: v1
kind: Service
metadata:
  name: nats-service
  labels:
    app: nats-core-bench
spec:
  # expose type for debugging outside of k8s
  # type: NodePort
  selector:
    app: nats-core-bench  
  ports:
  - name: nats-client
    port: 4222
    targetPort: 4222
  - name: http-monitor
    port: 8222
    targetPort: 8222
