apiVersion: batch/v1
kind: Job
metadata:
  name: stan-bench-sub
spec:
  template:
    metadata:
      name: stan-bench-sub
      labels:
        app: stan-bench
    spec:
      containers:
      - name: stan-bench
        imagePullPolicy: IfNotPresent
        image: stan-bench:latest
        args: ["-s", "nats://username:password@nats-service:4222", "-id", "stan-bench", "-a", "-np", "0", "-ns", "1", "-n", "100000", "foo"]
      restartPolicy: Never
  backoffLimit: 4
