apiVersion: batch/v1
kind: Job
metadata:
  name: nats-bench-pub
spec:
  template:
    metadata:
      name: nats-bench-pub
      labels:
        app: nats-core-bench
    spec:
      containers:
      - name: nats-bench
        imagePullPolicy: IfNotPresent
        image: nats-bench:latest
        args: ["-s", "nats://username:password@nats-service:4222", "-np", "1", "-ns", "0", "-n", "1000000", "foo"]
      restartPolicy: Never
  backoffLimit: 4
